development:
  sendgrid_username: apikey
  sendgrid_password: <%= ENV['SENDGRID_API_KEY'] %>

test:
  sendgrid_username: apikey
  sendgrid_password: <%= ENV['SENDGRID_API_KEY'] %>

production:
  sendgrid_username: apikey
  sendgrid_password: <%= ENV['SENDGRID_API_KEY'] %>
